### ISSUE TITLE
Using IPv6

### ISSUE THREAD

**Issue by VidarHUN** [c0r0n3r/dheater#14]
Hi,

I am trying to use dheater with an IPv6 address but I always get an error like below:

```
python3 -m dheater --protocol tls "[3011::4]:5060"
Network error oocuerd while checking whether Diffie-Hellman ephemeral (DHE) key exchange is supported by the server; uri="[3011::4]:5060", error="address of the target cannot be resolved"
```

How should I use or is it some kind of bug?

**Comment by c0r0n3r** [comment]
Please follow the issue on [GitLab](https://gitlab.com/dheatattack/dheater/-/issues/14).
